imageRegistry: docker.io

cmak:

  basicAuth:
    enabled: false
    username: ""
    password: ""

  clustersCommon:
    curatorConfig:
      zkMaxRetry: 100
      baseSleepTimeMs: 100
      maxSleepTimeMs: 1000
    enabled: true
    kafkaVersion: "2.2.0"
    jmxEnabled: false
    jmxUser: null
    jmxPass: null
    jmxSsl: false
    pollConsumers: true
    filterConsumers: false
    logkafkaEnabled: false
    activeOffsetCacheEnabled: true
    displaySizeEnabled: false
    tuning:
      brokerViewUpdatePeriodSeconds: 30
      clusterManagerThreadPoolSize: 10
      clusterManagerThreadPoolQueueSize: 100
      kafkaCommandThreadPoolSize: 10
      kafkaCommandThreadPoolQueueSize: 100
      logkafkaCommandThreadPoolSize: 10
      logkafkaCommandThreadPoolQueueSize: 100
      logkafkaUpdatePeriodSeconds: 30
      partitionOffsetCacheTimeoutSecs: 5
      brokerViewThreadPoolSize: 10
      brokerViewThreadPoolQueueSize: 1000
      offsetCacheThreadPoolSize: 10
      offsetCacheThreadPoolQueueSize: 1000
      kafkaAdminClientThreadPoolSize: 10
      kafkaAdminClientThreadPoolQueueSize: 1000
      kafkaManagedOffsetMetadataCheckMillis: 30000
      kafkaManagedOffsetGroupCacheSize: 1000000
      kafkaManagedOffsetGroupExpireDays: 7
    securityProtocol: PLAINTEXT
    saslMechanism: null
    jaasConfig: null

  clusters: []

reconcile:
  schedule: "*/2 * * * *"
  overwriteZk: true
  successfulJobsHistoryLimit: null
  failedJobsHistoryLimit: null

## Zookeeper containers' resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
zk:
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits: {}
    #   cpu: 100m
    #   memory: 128Mi
    requests: {}
    #   cpu: 100m
    #   memory: 128Mi

## UI containers' resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
ui:
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits: {}
    #   cpu: 100m
    #   memory: 128Mi
    requests: {}
    #   cpu: 100m
    #   memory: 128Mi
