{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "cmak.name" . | quote }}
  labels:
    {{- include "cmak.labels" . | nindent 4 }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ printf "%s-tls" .Values.ingress.host }}
  {{- end }}
{{- end }}
  rules:
    {{- if .Values.ingress.host }}
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ include "cmak.name" . | quote }}
              servicePort: {{ .Values.service.port }}
    {{- end }}
{{- end }}
